name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Lint (optional)
        run: |
          if [ -f package.json ] && jq -e '.scripts.lint' package.json > /dev/null; then
            npm run lint
          else
            echo "No lint script"
          fi
      - name: Run tests (optional)
        run: |
          if [ -f package.json ] && jq -e '.scripts.test' package.json > /dev/null; then
            npm test
          else
            echo "No test script"
          fi
      - name: Build (optional)
        run: |
          if [ -f package.json ] && jq -e '.scripts.build' package.json > /dev/null; then
            npm run build
          else
            echo "No build script"
          fi
